<?php

return [
    "home" => "dashboard_controller.php",
    "categoryList" => "category_controller.php",
    "categoryAdd" => "category_controller.php",
    "categoryDelete" => "category_controller.php",
    "categoryUpdate" => "category_controller.php",
    "productList" => "product_controller.php",
    "productAdd" => "product_controller.php",
    "productUpdate" => "product_controller.php",
    "productDelete" => "product_controller.php",
    "productDetail" => "product_controller.php",
    "productColor-List" => "product_controller.php",
    "views/admin/productColor-Add" => "product_controller.php",
    "productColor-Update" => "product_controller.php",
    "productColor-Delete" => "product_controller.php",
    "productMemory-List" => "product_controller.php",
    "productMemory-Add" => "product_controller.php",
    "productMemory-Update" => "product_controller.php",
    "productMemory-Delete" => "product_controller.php",
    "accountList" => "account_controller.php",
    "accountAdd" => "account_controller.php",
    "accountUpdate" => "account_controller.php",
    "accountDelete" => "account_controller.php",
    "commentList" => "comment_controller.php",
    "commentDelete" => "comment_controller.php",
    "orderList" => "order_controller.php",
    "orderDetail" => "order_controller.php",
    "orderDelete" => "order_controller.php",
    "orderUpdate" => "order_controller.php",
];
